version: '3.4'

services:
  redis:
    container_name: txqueue-redis
    image: redis:5.0.5
    restart: always
    environment: {}
    volumes:
      - ./redis/data/:/data
    expose:
      - 6379
    command: ["--appendonly", "yes"]
    
  txqueue:
    container_name: txqueue
    build:
      context: .
      dockerfile: Dockerfile
    image: txqueue:0.1.0
    # network_mode: host
    ports:
      - 8080:8080
    environment:
      REDIS_QUEUE_HOST: redis
      REDIS_QUEUE_PORT: 6379
      REDIS_QUEUE_DB: 0
      TASK_TIME: 3000
    depends_on:
      - redis
    


