---
swagger: "2.0"
info:
  description: "This is the Cellfie server. \n"
  version: "0.0.4"
  title: "Cellfie API"
  termsOfService: "http://cellfie.renci.org/TOS/"
  contact:
    email: "n4lewis@ucsd.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/cellfie/0.0.4"
tags:
- name: "scheduler"
  description: "Everything about scheduling your jobs"
  externalDocs:
    description: "Find out more"
    url: "http://cellfie.renci.org"
schemes:
- "https"
- "http"
paths:
  /scheduler/job:
    get:
      tags:
      - "scheduler"
      summary: "Lists queued jobs"
      description: "Returns a map of status codes to job ids"
      operationId: "get_job_queue"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
      x-swagger-router-controller: "swagger_server.controllers.scheduler_controller"
    post:
      tags:
      - "scheduler"
      summary: "Submit a job"
      operationId: "submit_job"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "job created for an analysis"
        required: true
        schema: {}
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Invalid Job"
      x-swagger-router-controller: "swagger_server.controllers.scheduler_controller"
  /scheduler/job/{jobId}:
    get:
      tags:
      - "scheduler"
      summary: "Find my job by Id"
      description: "For valid response try integer Ids with value >= 1 and <= 1000.\\\
        \ \\ Other values will generated exceptions"
      operationId: "get_job_by_id"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "jobId"
        in: "path"
        description: "Id of job to be fetched"
        required: true
        type: "integer"
        maximum: 10
        minimum: 1
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Invalid Id supplied"
        404:
          description: "Job not found"
      x-swagger-router-controller: "swagger_server.controllers.scheduler_controller"
    post:
      tags:
      - "scheduler"
      summary: "Resubmit a job"
      operationId: "resubmit_job"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "job created for an analysis"
        required: true
        schema:
          $ref: "#/definitions/Job"
      - name: "jobId"
        in: "path"
        description: "Id of job to be fetched"
        required: true
        type: "integer"
        maximum: 10
        minimum: 1
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Invalid Job"
      x-swagger-router-controller: "swagger_server.controllers.scheduler_controller"
    delete:
      tags:
      - "scheduler"
      summary: "Delete my job by Id"
      description: "For valid response try integer Ids with positive integer value.\\\
        \ \\ Negative or non-integer values will generate API errors"
      operationId: "delete_job"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "jobId"
        in: "path"
        description: "Id of the job that needs to be deleted"
        required: true
        type: "integer"
        minimum: 1
        format: "int64"
      responses:
        400:
          description: "Invalid Id supplied"
        404:
          description: "Job not found"
      x-swagger-router-controller: "swagger_server.controllers.scheduler_controller"
definitions:
  Job:
    type: "object"
    required:
    - "runId"
    - "scheduledTimestamp"
    - "status"
    - "user"
    properties:
      id:
        type: "integer"
        format: "int64"
      user:
        type: "string"
        example: "myname@mydomain.com"
      runId:
        type: "integer"
        format: "int64"
      scheduledTimestamp:
        type: "string"
        format: "date-time"
      submitTimestamp:
        type: "string"
        format: "date-time"
      systemRunTime:
        type: "string"
        format: "date-time"
      endTimestamp:
        type: "string"
        format: "date-time"
      analysisRequest: {}
      status:
        type: "string"
        description: "Job Status"
        default: "queued"
        enum:
        - "uploading"
        - "error"
        - "running"
        - "queued"
        - "finished"
        - "managingFiles"
        - "settingParameters"
        - "suspended"
        - "aborted"
    example:
      scheduledTimestamp: "2000-01-23T04:56:07.000+00:00"
      submitTimestamp: "2000-01-23T04:56:07.000+00:00"
      id: 0
      runId: 6
      systemRunTime: "2000-01-23T04:56:07.000+00:00"
      user: "myname@mydomain.com"
      endTimestamp: "2000-01-23T04:56:07.000+00:00"
      analysisRequest: ""
      status: "queued"
  GlobalOptions:
    type: "object"
    required:
    - "thresholdType"
    - "thresholdValue"
    properties:
      id:
        type: "integer"
        format: "int64"
      thresholdType:
        type: "string"
        default: "percentile"
        enum:
        - "percentile"
        - "absolute"
      thresholdValue:
        type: "string"
        example: "75"
  LocalOptions:
    type: "object"
    required:
    - "moreThanTwoSamples"
    - "thresholdMethod"
    properties:
      id:
        type: "integer"
        format: "int64"
      moreThanTwoSamples:
        type: "boolean"
        default: false
      thresholdMethod:
        type: "string"
        default: "mean"
        enum:
        - "minMaxMean"
        - "mean"
        - "custom"
      minimum:
        type: "string"
        example: "25"
      maximum:
        type: "string"
        example: "75"
      customLibraryUrl:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
