version: '3.4'

services:
    
  txqueue-worker:
    container_name: txqueue-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: txqueue-worker:0.1.0
    environment:
      REDIS_QUEUE_HOST: redis
      REDIS_QUEUE_PORT: 6379
      REDIS_QUEUE_DB: 0
      TASK_TIME: 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
    depends_on:
      - redis
      
 
    


